project:
  type: website
  output-dir: docs

website:
  title: "Andrew Carr"
  navbar:
    background: light
    right:
      - about.qmd
      - publications.qmd
      - icon: github
        href: https://github.com/AndrewCarr24
      - icon: linkedin
        href: https://www.linkedin.com/in/andrew-carr-a2aba232/
  page-footer:
    center: "<p>© <script>document.write(new Date().getFullYear())</script> Andrew Carr</p>"

format:
  html:
    theme:
      light: [flatly, custom.scss]
      dark: [darkly, custom-dark.scss]
    css: styles.css
  
execute:
  freeze: auto

